import type { Problem, TopicTag, PromoBanner } from "./types";

export const MOCK_PROMO_BANNERS: PromoBanner[] = [
  {
    id: "banner-1",
    title: "Learn Basics of Your Competition",
    description: "New to CodeWars DSA speed battles? Dive into key rules and setup your workspace.",
    link: "/docs/competition-basics",
    bgPattern: "linear-gradient(135deg, rgba(224, 70, 70, 0.15) 0%, rgba(9, 9, 11, 0) 100%)",
  },
  {
    id: "banner-2",
    title: "Learn Queue in Interactive Course",
    description: "Understand FIFO queues, circular queues, and implementation in live code arenas.",
    link: "/courses/queue",
    bgPattern: "linear-gradient(135deg, rgba(94, 168, 217, 0.15) 0%, rgba(9, 9, 11, 0) 100%)",
  },
  {
    id: "banner-3",
    title: "Learn Stack with Interactive Course",
    description: "Explore LIFO structures, recursion, and prefix/postfix parsing.",
    link: "/courses/stack",
    bgPattern: "linear-gradient(135deg, rgba(201, 162, 39, 0.15) 0%, rgba(9, 9, 11, 0) 100%)",
  },
  {
    id: "banner-4",
    title: "Tackle Dynamic Programming",
    description: "From Fibonacci to Knapsack. Master optimization by caching subproblem solutions.",
    link: "/courses/dynamic-programming",
    bgPattern: "linear-gradient(135deg, rgba(16, 185, 129, 0.15) 0%, rgba(9, 9, 11, 0) 100%)",
  },
];

export const MOCK_TOPIC_TAGS: TopicTag[] = [
  { label: "All", count: 1200, category: "all" },
  { label: "Array", count: 1234, category: "Algorithms" },
  { label: "String", count: 768, category: "Algorithms" },
  { label: "Hash Table", count: 521, category: "Algorithms" },
  { label: "Dynamic Programming", count: 432, category: "Algorithms" },
  { label: "Sorting", count: 300, category: "Algorithms" },
  { label: "Math", count: 250, category: "Algorithms" },
  { label: "Greedy", count: 210, category: "Algorithms" },
  { label: "Depth-First Search", count: 180, category: "Algorithms" },
  { label: "Database", count: 150, category: "Database" },
  { label: "Binary Search", count: 140, category: "Algorithms" },
  { label: "Breadth-First Search", count: 130, category: "Algorithms" },
  { label: "Tree", count: 120, category: "Algorithms" },
  { label: "Matrix", count: 110, category: "Algorithms" },
  { label: "Two Pointers", count: 100, category: "Algorithms" },
  { label: "Bit Manipulation", count: 90, category: "Algorithms" },
  { label: "Design", count: 70, category: "Algorithms" },
  { label: "Stack", count: 60, category: "Algorithms" },
  { label: "Heap (Priority Queue)", count: 50, category: "Algorithms" },
  { label: "Backtracking", count: 45, category: "Algorithms" },
  { label: "Graph", count: 40, category: "Algorithms" },
  { label: "Sliding Window", count: 35, category: "Algorithms" },
  { label: "Union Find", count: 30, category: "Algorithms" },
  { label: "Linked List", count: 25, category: "Algorithms" },
  { label: "Trie", count: 20, category: "Algorithms" },
  { label: "Recursion", count: 15, category: "Algorithms" },
];

export const MOCK_PROBLEMS: Problem[] = [
  {
    id: "p1",
    index: 1,
    title: "Two Sum",
    slug: "two-sum",
    acceptanceRate: 52.3,
    difficulty: "Easy",
    status: "solved",
    category: "Algorithms",
    tags: ["Array", "Hash Table"],
  },
  {
    id: "p2",
    index: 2,
    title: "Add Two Numbers",
    slug: "add-two-numbers",
    acceptanceRate: 41.5,
    difficulty: "Medium",
    status: "attempted",
    category: "Algorithms",
    tags: ["Linked List", "Math"],
  },
  {
    id: "p3",
    index: 3,
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring-without-repeating-characters",
    acceptanceRate: 34.2,
    difficulty: "Medium",
    status: "solved",
    category: "Algorithms",
    tags: ["Hash Table", "String", "Sliding Window"],
  },
  {
    id: "p4",
    index: 4,
    title: "Median of Two Sorted Arrays",
    slug: "median-of-two-sorted-arrays",
    acceptanceRate: 38.6,
    difficulty: "Hard",
    status: "todo",
    category: "Algorithms",
    tags: ["Array", "Binary Search", "Divide and Conquer"],
  },
  {
    id: "p5",
    index: 5,
    title: "Longest Palindromic Substring",
    slug: "longest-palindromic-substring",
    acceptanceRate: 32.8,
    difficulty: "Medium",
    status: "todo",
    category: "Algorithms",
    tags: ["String", "Dynamic Programming"],
  },
  {
    id: "p6",
    index: 6,
    title: "Zigzag Conversion",
    slug: "zigzag-conversion",
    acceptanceRate: 46.1,
    difficulty: "Medium",
    status: "todo",
    category: "Algorithms",
    tags: ["String"],
  },
  {
    id: "p7",
    index: 7,
    title: "Reverse Integer",
    slug: "reverse-integer",
    acceptanceRate: 28.3,
    difficulty: "Medium",
    status: "solved",
    category: "Algorithms",
    tags: ["Math"],
  },
  {
    id: "p8",
    index: 8,
    title: "String to Integer (atoi)",
    slug: "string-to-integer-atoi",
    acceptanceRate: 17.2,
    difficulty: "Medium",
    status: "attempted",
    category: "Algorithms",
    tags: ["String"],
  },
  {
    id: "p9",
    index: 9,
    title: "Palindrome Number",
    slug: "palindrome-number",
    acceptanceRate: 54.9,
    difficulty: "Easy",
    status: "solved",
    category: "Algorithms",
    tags: ["Math"],
  },
  {
    id: "p10",
    index: 10,
    title: "Regular Expression Matching",
    slug: "regular-expression-matching",
    acceptanceRate: 28.0,
    difficulty: "Hard",
    status: "todo",
    category: "Algorithms",
    tags: ["String", "Dynamic Programming", "Recursion"],
  },
  {
    id: "p11",
    index: 11,
    title: "Container With Most Water",
    slug: "container-with-most-water",
    acceptanceRate: 54.5,
    difficulty: "Medium",
    status: "solved",
    category: "Algorithms",
    tags: ["Array", "Two Pointers"],
  },
  {
    id: "p12",
    index: 12,
    title: "Integer to Roman",
    slug: "integer-to-roman",
    acceptanceRate: 63.4,
    difficulty: "Medium",
    status: "todo",
    category: "Algorithms",
    tags: ["Math", "String"],
  },
  {
    id: "p13",
    index: 13,
    title: "Roman to Integer",
    slug: "roman-to-integer",
    acceptanceRate: 58.7,
    difficulty: "Easy",
    status: "solved",
    category: "Algorithms",
    tags: ["Math", "String"],
  },
  {
    id: "p14",
    index: 14,
    title: "Longest Common Prefix",
    slug: "longest-common-prefix",
    acceptanceRate: 42.1,
    difficulty: "Easy",
    status: "solved",
    category: "Algorithms",
    tags: ["String"],
  },
  {
    id: "p15",
    index: 15,
    title: "3Sum",
    slug: "3sum",
    acceptanceRate: 33.5,
    difficulty: "Medium",
    status: "todo",
    category: "Algorithms",
    tags: ["Array", "Two Pointers", "Sorting"],
  },
  {
    id: "p19",
    index: 19,
    title: "Remove Nth Node From End of List",
    slug: "remove-nth-node-from-end-of-list",
    acceptanceRate: 43.8,
    difficulty: "Medium",
    status: "todo",
    category: "Algorithms",
    tags: ["Linked List", "Two Pointers"],
  },
  {
    id: "p20",
    index: 20,
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    acceptanceRate: 40.5,
    difficulty: "Easy",
    status: "solved",
    category: "Algorithms",
    tags: ["String", "Stack"],
  },
  {
    id: "p21",
    index: 21,
    title: "Merge Two Sorted Lists",
    slug: "merge-two-sorted-lists",
    acceptanceRate: 63.1,
    difficulty: "Easy",
    status: "solved",
    category: "Algorithms",
    tags: ["Linked List", "Recursion"],
  },
  {
    id: "p22",
    index: 22,
    title: "Generate Parentheses",
    slug: "generate-parentheses",
    acceptanceRate: 73.5,
    difficulty: "Medium",
    status: "todo",
    category: "Algorithms",
    tags: ["String", "Dynamic Programming", "Backtracking"],
  },
  {
    id: "p175",
    index: 175,
    title: "Combine Two Tables",
    slug: "combine-two-tables",
    acceptanceRate: 74.2,
    difficulty: "Easy",
    status: "solved",
    category: "Database",
    tags: ["Database"],
  },
  {
    id: "p176",
    index: 176,
    title: "Second Highest Salary",
    slug: "second-highest-salary",
    acceptanceRate: 37.8,
    difficulty: "Medium",
    status: "todo",
    category: "Database",
    tags: ["Database"],
  },
  {
    id: "p192",
    index: 192,
    title: "Word Frequency",
    slug: "word-frequency",
    acceptanceRate: 26.5,
    difficulty: "Medium",
    status: "todo",
    category: "Shell",
    tags: ["Shell"],
  },
  {
    id: "p1114",
    index: 1114,
    title: "Print in Order",
    slug: "print-in-order",
    acceptanceRate: 68.3,
    difficulty: "Easy",
    status: "solved",
    category: "Concurrency",
    tags: ["Concurrency"],
  },
  {
    id: "p2620",
    index: 2620,
    title: "Counter",
    slug: "counter",
    acceptanceRate: 89.4,
    difficulty: "Easy",
    status: "solved",
    category: "JavaScript",
    tags: ["JavaScript"],
  },
  {
    id: "p2635",
    index: 2635,
    title: "Apply Transform Over Each Element in Array",
    slug: "apply-transform-over-each-element-in-array",
    acceptanceRate: 87.2,
    difficulty: "Easy",
    status: "solved",
    category: "JavaScript",
    tags: ["JavaScript"],
  },
];
